services:

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile_backend
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    environment:
      DATABASE: database
    networks:
      - web_app_network
    ports:
      - '127.0.0.1:8000:8000'
    command: >
      sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - database

  database:
    image: postgres:15-alpine3.18
    container_name: database
    volumes:
      - data_db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - web_app_network
    restart: always


networks:
  web_app_network:
    driver: bridge

volumes:
  data_db: